version: '3.0'

services:
  jenkins:
      build: 
        context: jenkins/
      volumes:
        - ./jenkins_volume/:/var/jenkins_home/
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
      - "8080:8080" 
      - "50000:50000"
      networks:
        - frontend
  
  app:
    build:
      context: .
    ports:
      - "8081:8080"
    networks:
      - frontend
  
  gotify:
    image: gotify/server
    ports:
      - "81:80"
    networks:
      - frontend

networks:

  frontend:
    driver: bridge